In [1]:
import numpy as np

In [6]:
x=np.array([10,4,36,22,100,64,8])
x

array([ 10,   4,  36,  22, 100,  64,   8])

In [7]:
np.sqrt(x)

array([ 3.16227766,  2.        ,  6.        ,  4.69041576, 10.        ,
        8.        ,  2.82842712])

In [9]:
np.power(x,2)

array([  100,    16,  1296,   484, 10000,  4096,    64], dtype=int32)

In [15]:
y = [4,62,31,8,7,3,21]
y

[4, 62, 31, 8, 7, 3, 21]

In [16]:
np.maximum(x,y)

array([ 10,  62,  36,  22, 100,  64,  21])

In [17]:
np.array(y)

array([ 4, 62, 31,  8,  7,  3, 21])

# np.where

In [19]:
import numpy as np

In [20]:
sal=np.array([0,-5,5000,15000])
sal

array([    0,    -5,  5000, 15000])

In [22]:
np.where(sal<=0,25000,sal)

array([25000, 25000,  5000, 15000])

In [23]:
np.where(sal<=0,"Not OK","OK")

array(['Not OK', 'Not OK', 'OK', 'OK'], dtype='<U6')

In [24]:
li=[200,500,900,1500,50,35,20,4500]

In [26]:
lis=np.array(li)
lis

array([ 200,  500,  900, 1500,   50,   35,   20, 4500])

In [28]:
np.where(lis<=100,"lower","upper")

array(['upper', 'upper', 'upper', 'upper', 'lower', 'lower', 'lower',
       'upper'], dtype='<U5')

# Mathmatical & Statical methods

In [29]:
import numpy as np

In [30]:
x=np.array([10,9,7,8,10,7])
x

array([10,  9,  7,  8, 10,  7])

In [31]:
x.mean()

8.5

In [32]:
x.cumsum()

array([10, 19, 26, 34, 44, 51], dtype=int32)

In [33]:
x.cumprod()

array([    10,     90,    630,   5040,  50400, 352800], dtype=int32)

In [38]:
y=(x<9)
y

array([False, False,  True,  True, False,  True])

In [39]:
y.sum()

3

In [40]:
y.any()

True

In [41]:
y.all()

False

In [45]:
y=x>9
y

array([ True, False, False, False,  True, False])

In [46]:
y.sum()

2

In [48]:
x.sort()
x

array([ 7,  7,  8,  9, 10, 10])

In [49]:
y.sort()
y

array([False, False, False, False,  True,  True])